/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class shmem */

#ifndef _Included_shmem
#define _Included_shmem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     shmem
 * Method:    get_handle
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_shmem_get_1handle
  (JNIEnv *, jobject);

/*
 * Class:     shmem
 * Method:    get_next_frame
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_shmem_get_1next_1frame
  (JNIEnv *, jobject, jlong);

/*
 * Class:     shmem
 * Method:    get_content_buffer
 * Signature: (J)[Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobjectArray JNICALL Java_shmem_get_1content_1buffer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     shmem
 * Method:    get_foreground_color_buffer
 * Signature: (J)[Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobjectArray JNICALL Java_shmem_get_1foreground_1color_1buffer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     shmem
 * Method:    get_background_color_buffer
 * Signature: (J)[Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobjectArray JNICALL Java_shmem_get_1background_1color_1buffer
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
